JamiatAhleHadees/Areas/Admin/Controllers/UserRegistrationController.cs
using BusinessLayer.Implementation;
using CommonLayer.CommonModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace JamiatAhleHadees.Areas.Admin.Controllers
{
    [AllowAnonymous]
    public class UserRegistrationController : Controller
    {
        private readonly UserModel _userModel;
        private readonly UserRegistrationBs _userRegistrationBs;
        public UserRegistrationController()
        {
            _userModel = new UserModel();
            _userRegistrationBs = new UserRegistrationBs();
        }

        public ActionResult Index(int i)
        {

            var varial = _userRegistrationBs.UserRegistrationList();
            return View(varial);
        }

        public ActionResult Create(int? id)
        {
            if (id != null)
            {
                var Varial = _userRegistrationBs.GetById(Convert.ToInt32(id));

                return View(Varial);

            }
            else
            {

                _userModel.UserLists = _userRegistrationBs.UserRegistrationList().ToList();

                return View(_userModel);

            }

        }

        [HttpPost]
        public ActionResult Create(UserModel model)
        {
            int i = 0;

            if (model != null)
            {
            i= _userRegistrationBs.Save(model);
            }

            if (i>0)
            {
                TempData["msg"] = "Registered Successfully";
            }
            else
            {
                TempData["msg"] = " Not Registered ";
            }
                
            return  RedirectToAction("Index", "Login", new { area = "User" });
         
        }
    }
}

JamiatAhleHadees/Areas/Admin/Views/UserRegistration/Create.cshtml
@model CommonLayer.CommonModels.UserModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->

    <link href="~/Assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->

    <link href="~/Assets/dist/css/AdminLTE.min.css" rel="stylesheet" />
    <!-- iCheck -->
    <link href="~/Assets/plugins/iCheck/square/blue.css" rel="stylesheet" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<br />

<div class="box-header with-border">
    <h3 style="text-align:center">New Registration</h3>
</div>
<br />

@using (Html.BeginForm("Create", "UserRegistration", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    if (ViewBag.Success != null)
    {
        <div class="callout callout-success">
            <h4>
                @ViewBag.Success

            </h4>
            <p>Please Login with your Credentials.</p>
        </div>
    }

    <div class="container ">
        <div class="col-md-4 col-lg-offset-4">

            <form class="form-horizontal form-label-left">

                <div class="form-group row">
                    <label for="example-search-input" class="col-2 col-form-label">Full Name</label>
                    <div class="col-6">
                        <input type="text" id="Name" value="@Model.Name" name="Name" class="form-control" placeholder="User Name" />
                    </div>
                </div>

                <div class="form-group row">
                    <label for="example-search-input" class="col-2 col-form-label">Contact</label>
                    <div class="col-5">
                        <input type="text" id="Contact" value="@Model.Contact" name="Contact" class="form-control" placeholder="Contact" />
                    </div>
                </div>

                <div class="form-group row">
                    <label for="example-search-input" class="col-2 col-form-label">Email Address</label>
                    <div class="col-5">
                        <input type="email" id="Email" value="@Model.Email" name="Email" class="form-control" placeholder="Email Address" />
                    </div>
                </div>

                <div class="form-group row">
                    <label for="example-search-input" class="col-2 col-form-label">User Name</label>
                    <div class="col-5">
                        <input type="text" id="UserName" value="@Model.UserName" name="UserName" class="form-control" placeholder="User Name" style="word-spacing:unset" />
                    </div>
                </div>

                <div class="form-group row">
                    <label for="example-search-input" class="col-2 col-form-label">Password</label>
                    <div class="col-5">
                        <input type="Password" id="Password" value="@Model.Password" name="Password" class="form-control" placeholder="********" />
                    </div>
                </div>


                <div class="form-group row">
                    <label for="example-search-input" class="col-2 col-form-label">Area</label>
                    <div class="col-5">
                        <input type="text" id="Area" value="@Model.Area" name="Area" class="form-control" placeholder="Area" />
                    </div>
                </div>

                <div class="form-group row">
                    <label for="example-search-input" class="col-2 col-form-label">Profile Pic</label>
                    <div class="col-5">
                        <input type="file" id="ProfilePic" name="Files" class="form-control" placeholder="" />
                    </div>
                </div>


                <div class="form-group row">
                    <div class="col-md-5">
                        @if (Model.Id != null && Model.Id != 0)
                        {
                            <button type="submit" class="btn-block btn btn-success" data-id="@Model.Id" id="btnRegisterUpdate">
                                Update
                            </button>
                        }
                        else
                        {
                            <button type="submit" class="btn-block btn btn-success" data-id="0" id="btnRegister">
                                Register
                            </button>
                        }
                    </div>
                    <div class="col-md-5">
                        <button value="Edit"
                                class="btn-block btn btn-danger" type="button" id="addressSearch"
                                onclick="location.href='@Url.Action("Index", "Login",new { area="User"})'">
                            Cancel
                        </button>
                    </div>
                </div>

            </form>

        </div>
    </div>
}